# Для yandex cloud 
name: Deploy VentSearch
on:
  push:
    branches: [ main ] # Сработает при пуше в ветку main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Авторизация в облаке через твой секретный ключ
      - name: Login to Yandex Container Registry
        uses: yc-actions/yc-cr-login@v1
        with:
          yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_KEY }}

      # Сборка Docker-образа бэкенда
      - name: Build and Push Docker Image
        run: |
          docker build -t cr.yandex/${{ secrets.REGISTRY_ID }}/ventsearch-api:latest -f Dockerfile .
          docker push cr.yandex/${{ secrets.REGISTRY_ID }}/ventsearch-api:latest

      # Обновление контейнера в Serverless Containers
      - name: Deploy Revision
        run: |
          # Установка CLI Yandex Cloud на сервер GitHub
          curl -sSL https://storage.yandexcloud.net/yandexcloud-designers/install.sh | bash
          export PATH=$PATH:/home/runner/yandex-cloud/bin
          
          # Авторизация CLI
          echo '${{ secrets.YC_SA_JSON_KEY }}' > key.json
          yc config profile create sa-profile
          yc config set service-account-key key.json
          
          # Сама команда деплоя
          yc serverless container revision deploy \
            --container-name ventsearch-api \
            --image cr.yandex/${{ secrets.REGISTRY_ID }}/ventsearch-api:latest \
            --cores 1 \
            --memory 512M \
            --concurrency 8 \
            --execution-timeout 30s

