# Для yandex cloud 
name: Deploy VentSearch
on:
  push:
    branches: [ baranovegor ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Yandex Container Registry
        uses: yc-actions/yc-cr-login@v1
        with:
          yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_KEY }}

      - name: Build and Push Docker Image
        run: |
          docker build -t cr.yandex/${{ secrets.REGISTRY_ID }}/ventsearch-api:${{ github.sha }} -f Dockerfile .
          docker push cr.yandex/${{ secrets.REGISTRY_ID }}/ventsearch-api:${{ github.sha }}

      # # Используем официальный экшен для деплоя
      # - name: Deploy Serverless Container
      #   uses: yc-actions/deploy-serverless-container@v1
      #   with:
      #     yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_KEY }}
      #     container-name: ventsearch-api
      #     folder-id: ${{ secrets.FOLDER_ID }}
      #     revision-image: cr.yandex/${{ secrets.REGISTRY_ID }}/ventsearch-api:${{ github.sha }}
      #     revision-cores: 1
      #     revision-memory: 512Mb
      #     revision-concurrency: 8

# Используем ПРАВИЛЬНЫЙ экшен для деплоя
      - name: Deploy Serverless Container
        uses: yandex-cloud/deploy-container@v1 # Исправлено здесь
        with:
          yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_KEY }}
          container-name: ventsearch-api
          folder-id: ${{ secrets.FOLDER_ID }}
          revision-image: cr.yandex/${{ secrets.REGISTRY_ID }}/ventsearch-api:${{ github.sha }}
          revision-cores: 1
          revision-memory: 512Mb
          revision-concurrency: 8